### ISSUE TITLE
多选，点击原图崩溃

### ISSUE THREAD

**Issue by MQZHot** [February12/YLImagePickerController#3]
![12](https://user-images.githubusercontent.com/17667368/34925766-5cbb43e4-f9e6-11e7-866a-051ea0027bda.jpg)

**Comment by February12** [comment]
可以将报错的信息发给我? 845369698

**Comment by February12** [comment]
@MQZHot

**Comment by MQZHot** [comment]
直接崩在Appdelegate了

**Comment by February12** [comment]
@MQZHot  什么环境下， 点击原图这个按钮后就直接崩溃？还是选了原图后点击 发送后崩溃？

**Comment by MQZHot** [comment]
进入这个界面，点击原图这个按钮就崩溃了。

**Comment by February12** [comment]
@MQZHot  你在 YLPhotoBrowser 类里面把 135 行 改成 #selector(YLPhotoBrowser.originalImageClickBtnHandle) 和 189 行 方法前加一个 @objc 。就解决了。 非常抱歉。   cocoapods  会在下一版本更新这个问题

**Comment by MQZHot** [comment]
😆
